version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns,sqs
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./localstack:/etc/localstack/init/ready.d

  postgres-products:
    image: postgres:16
    container_name: postgres-products
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres-delivery-man:
    image: postgres:16
    container_name: postgres-delivery-man
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: delivery_man
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres/delivery-man-init.sql:/docker-entrypoint-initdb.d/init.sql